// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yofkedyivinggmmmozjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZmtlZHlpdmluZ2dtbW1vemprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjkyNTUsImV4cCI6MjA2NzQ0NTI1NX0.6K9mg81JpfbC8Fb5jpnULNAB4SZY4KHQcMbQR_fNPXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});